serverName: Clumsy's World: Resurgence
filelistUrl: https://patch.clumsysworld.com/
patchNotesUrl: https://patch.clumsysworld.com/patch-notes.md
defaultAutoPatch: false
defaultAutoPlay: false
supportedClients:
  - Rain_Of_Fear_2
  - Rain_Of_Fear_2_4GB
